spring:
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/mmall?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  #    username: root
  #    password: lk123456
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: none
  redis:
    host: localhost
    port: 6379


server:
  port: 8081
  servlet:
    session:
      timeout: 30m
  error:
    path: /error

mybatis:
  mapper-locations: classpath:mappers/*.xml

management:
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info', "env", 'httptrace', 'metrics', 'prometheus' ]
  endpoint:
    health:
      show-components: always
      show-details: always
    httptrace:
      enabled: true
  metrics:
    enable:
      jvm: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    export:
      prometheus:
        enabled: true
  health:
    jms:
      enabled: false


app-config:
  test-enabled: true
  include-error-trace: true
  alipay-callback-url: http://wimxtf.natappfree.cc/order/alipay_callback.do
  redis-lock-time: 5000
  img-path: /img/
  security:
    validation:
      sms:
        lenghth: 6
        expire: 300
        url: /users,/user/*
  ftp:
    server: 127.0.0.1
    port: 22
    username: test
    password: test
  jwt:
    secret-key: secret-key-155b0e48-f9a4-4a17-978d-286eacb410a4-a9487855-1bd3-4878-82e9-d73e811a6639-083018bc-3655-473e-a33f-d49a960e781a-0c53d4a0-0b4e-4c4e-a42e-253c138a41f7-0c53d4a0-0b4e-4c4e-a42e-253c138a41f7-0c53d4a0-0b4e-4c4e-a42e-253c138a41f7-0c53d4a0-0b4e-4c4e-a42e-253c138a41f7
    expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
