spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mmall?characterEncoding=utf-8
    username: root
    password: lk123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
#    dbcp2:
#      initial-size:

server:
  port: 8081
  servlet:
    session:
      timeout: 30m

mybatis:
  mapper-locations: classpath:mappers/*.xml
