application:
  test:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mmall?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: lk123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  #  redis:
  #    host: localhost
  #    port: 6379

  session:
    store-type: none

server:
  port: 8081
  servlet:
    session:
      timeout: 30m

mybatis:
  mapper-locations: classpath:mappers/*.xml

