application:
  test:
    enabled: true
  security:
    validation:
      sms:
        lenghth: 6
        expire: 60
        url: /users,/user/*


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mmall?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: lk123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: none
  redis:
    host: localhost
    port: 6379


server:
  port: 8081
  servlet:
    session:
      timeout: 30m

mybatis:
  mapper-locations: classpath:mappers/*.xml
